runo/urls.py
from . import views
from django.urls import path, include

app_name = 'runo'
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('', views.index, name='index'),
   # path('searchBase/', views.searchBase, name='searchBase'),
    path('news/<str:slug>/<int:year>/<int:month>/<int:day>/', views.news, name='news'),
    path('gallery/', views.gallery, name='gallery'),
    path('about/', views.aboutUs, name='about'),
    path('academics/', views.academics, name='academics'),
    
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('password_change/', views.change_password, name='change_password'),
    
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    
    path('register/', views.register, name='register'),
    path('teacher/', views.teacher, name='teacher'),
    path('result_page/<str:Class>/<str:username>/', views.result_page, name='result_page'),
    path('result/<str:Class>/<str:username>/', views.result, name='result'),
    path('changeclass/<str:Class>/<str:username>/<str:status>', views.changeclass, name='changeclass' ),
    path('pupil/', views.pupil, name='pupil'),
    path('updateProfile/', views.updateProfile, name='updateProfile'),
    path('sendMsg/', views.sendMsg, name='sendMsg'),
    path('viewResults/<str:Class>/', views.viewResults, name='viewResults'),
    
    path('msg_for_admin/<int:id>/', views.msg_for_admin, name='msg_for_admin'),
    path('admin_msgs/', views.msg_for_admin2, name='msg_for_admin2'),
    path('admin_update_user/<str:username>/', views.admin_update_user, name='admin_update_user'),
    
    path('adminPanel/', views.adminPanel, name='adminPanel'),
    path('message_all_users/', views.message_all_users, name='message_all_users'),
    path('viewSchoolMessage/', views.viewSchoolMessage, name='viewSchoolMessage')
    
]

runoschool/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('runo.urls', namespace='runo')),
    # path('', include('django.contrib.auth.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

runo/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import UserClass, UserProfile

class Register(forms.ModelForm):
    classifier = [('not_sure', 'not sure'), ('is_student', 'Student'), ('is_teacher', 'Teacher')]
    class Meta:
        model = User
        fields = ['username', 'email', 'first_name', 'last_name']
        
        
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Retype Password', widget=forms.PasswordInput)
    usertype = forms.ChoiceField(choices=classifier)
    
    def verify_password(self):
        password1 = self.cleaned_data['password1']
        password2 = self.cleaned_data['password2']
        if len(password1) < 6 or len(password2) < 6:
            raise forms.ValidationError('Password must be at least six characters long')
            return None
        
        elif password1 != password2:
            raise forms.ValidationError('Passwords do not match')
            return None
        
        else:
            return self.password1
    
class UserClassName(forms.Form):
    classes = [('1', 'Pre-Nursery'), ('2', 'Nursery 1'), ('3', 'Nursery 2'), ('4', 'Nursery 3'),
               ('5', 'Basic 1'), ('6', 'Basic 2'), ('7', 'Basic 3'), ('8', 'Basic 4'),
               ('9', 'Basic 5'), ('10', 'Basic 6')]
    Class = forms.ChoiceField(choices=classes)
    
class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ['profile_image', 'status']    
    

runo/views.py
from django.shortcuts import render, reverse
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.shortcuts import get_object_or_404
import datetime
from django.core.mail import send_mail

from .models import Intro, News, ImportantDates, FooterDetails, Gallery, AboutSchool, Academics, UserClass, Result, AllResults
from .models import UserProfile, Message
from .forms import UserClassName, UserProfileForm
from django.db.models import Q

# Create your views here.

#def searchBase(request):
    
        
        
def index(request):
    introImgs = Intro.objects.all().order_by('-uploaded')[:1]
    news = News.objects.filter(publish=True).order_by('-published').all()[:6]
    dates = ImportantDates.objects.filter(date__gte=datetime.date.today()).order_by('date')[:12]
    
    try:
        aboutSchool = FooterDetails.objects.all().order_by('-id')[0] 
    except:
        aboutSchool = None
    
    allNews = None
    if request.method == 'POST':
        searchData = request.POST['searchData']
        newsSearch = News.objects.filter(Q(title__icontains=searchData) | Q(newsBody__icontains=searchData) | Q(desc__icontains=searchData)).all() 
        events = ImportantDates.objects.filter(event__icontains=searchData).all()
        
        allNews = newsSearch
    
    
    # Show upcoming events 14 days prior
    upcoming_event = None
    if len(dates) > 0:
        closest_event = 100000
        for upcoming in dates:
            
            time = ( datetime.date(upcoming.date.year, upcoming.date.month, upcoming.date.day) - datetime.date.today()).days
            if time < closest_event and time > -1:
                closest_event = time
            if time < 14 and time <= closest_event and time > -1:
                upcoming_event = {'upcoming': upcoming, 'time': time }
            
    if len(introImgs) > 0:
        introImg = []
        for intro in introImgs:
            details = {
                'img': intro.img.url,
                'schoolName': intro.schoolName,
                'desc': intro.desc
            }
            introImg.append(details)
            
        return render(request, 'runo/index.html', {'section': 'home', 'allNews': allNews,
                                                   'introImg': introImg,
                                                   'news': news, 'upcoming_event': upcoming_event,
                                                   'dates': dates, 'aboutSchool': aboutSchool})

    return render(request, 'runo/index.html', {'section': 'home', 'news': news, 'allNews': allNews,
                                               'upcoming_event': upcoming_event,
                                               'dates': dates, 'aboutSchool': aboutSchool})


def news(request, slug, year, month, day):
    newsItem = News.objects.filter(slug=slug, published__day=day,
                                 published__month=month, published__year=year).first()
    
    news = News.objects.filter(publish=True).order_by('-published').all()[:6]
    try:
        aboutSchool = FooterDetails.objects.all().order_by('-id')[0] 
    except:
        aboutSchool = None
    return render(request, 'runo/news.html', {'aboutSchool': aboutSchool, 'newsItem': newsItem, 'news': news})


def gallery(request):
    gallery = Gallery.objects.filter(display=True).order_by('-uploaded').all()
    try:
        aboutSchool = FooterDetails.objects.all().order_by('-id')[0] 
    except:
        aboutSchool = None
    return render(request, 'runo/gallery.html', {'galleries': gallery, 'aboutSchool': aboutSchool})



def aboutUs(request):
    newsItem = AboutSchool.objects.filter(publish=True).order_by('-published').first()
    news = News.objects.filter(publish=True).order_by('-published').all()[:6]
    try:
        aboutSchool = FooterDetails.objects.all().order_by('-id')[0] 
    except:
        aboutSchool = None
    return render(request, 'runo/about.html', {'aboutSchool': aboutSchool, 'newsItem': newsItem, 'news': news, 'section': 'about'})

from django.contrib.auth.models import Group, Permission
from django.contrib.auth.decorators import login_required, permission_required


def academics(request):
    newsItem = Academics.objects.order_by('-published').first()
    news = News.objects.filter(publish=True).order_by('-published').all()[:6]
    try:
        aboutSchool = FooterDetails.objects.all().order_by('-id')[0] 
    except:
        aboutSchool = None
    
    return render(request, 'runo/about.html', {'aboutSchool': aboutSchool, 'newsItem': newsItem, 'news': news, 'section': 'academics'})



# Student Management System
from .models import Users
from django.contrib.auth.models import Group, Permission
from django.contrib.contenttypes.models import ContentType
from django.contrib.auth.models import User
from .forms import Register


teacher_group = None
pupil_group = None

# teacher_group, created = Group.objects.get_or_create(name='teacher_group')
# ct = ContentType.objects.get_for_model(Users)
                
# permission = Permission.objects.filter(codename='is_teacher', name='is_teacher', content_type=ct).first()
# teacher_group.permissions.add(permission)


# pupil_group, created = Group.objects.get_or_create(name='pupil_group')
# Content_type = ContentType.objects.get_for_model(Users)
# pupil_permission = Permission.objects.filter(codename='is_pupil', name='is_pupil', content_type=Content_type).first()
# pupil_group.permissions.add(pupil_permission)

#@staff_member_required
def register(request):
    form = Register()
    form2 = UserClassName()
    try:
        aboutSchool = FooterDetails.objects.all().order_by('-id')[0] 
    except:
        aboutSchool = None
    context = {'form': form, 'form2': form2, 'section': 'register', 'aboutSchool': aboutSchool}
    return_file = render(request, 'registration/login.html', context)
    if request.method == 'POST':
        form = Register(request.POST)
        form2 = UserClassName(data=request.POST)
        if form.is_valid() and form2.is_valid():
            password1 = form.cleaned_data['password1']
            password2 = form.cleaned_data['password2']
            email = form.cleaned_data['email']
            used_email = User.objects.filter(email=email).first()
            user_type = form.cleaned_data['usertype']
            user_class = form2.cleaned_data['Class']
            
            if used_email:
                context['error_msg'] = 'Email address already in use'
                return render(request, 'registration/login.html', context)
                
            if password1 != password2:
                context['error_msg'] = 'Passwords do not match'
                return render(request, 'registration/login.html', context)
            elif len(password1) < 6:
                context['error_msg'] = 'password must be at least six characters long'
                return render(request, 'registration/login.html', context)
            
            else:
                new_user = form.save(commit=False)
                new_user.set_password(password1)
                
                new_user.save()
                
                
                
                
                if user_type == 'is_teacher':
                    class_for_user = UserClass(Class=user_class, is_student=False, is_teacher=True)
                    class_for_user.save()
                    class_for_user.users.add(new_user)
                    class_for_user.save()
                    new_user.groups.add(teacher_group)
                    
                    new_user_profile = UserProfile(user=new_user)
                    new_user_profile.save()
                    
                    msg = 'User registered as teacher'
                    
                elif user_type == 'is_student':
                    
                    class_for_user = UserClass(Class=user_class, is_student=True)
                    class_for_user.save()
                    class_for_user.users.add(new_user)
                    class_for_user.save()
                    result = Result(user=new_user, current_class=user_class)
                    result.save()
                
                    new_user.groups.add(pupil_group)
                    
                    new_user_profile = UserProfile(user=new_user)
                    new_user_profile.save()
                    
                    msg = 'User registered as pupil'
                    
                elif user_type == 'not_sure':
                    class_for_user = UserClass(Class=user_class, is_student=False)
                    class_for_user.save()
                    class_for_user.users.add(new_user)
                    class_for_user.save()
                    
                    new_user_profile = UserProfile(user=new_user)
                    new_user_profile.save()
                    
                    msg = 'User saved, but has not ben assigned a role'
                    
                    
                
                context['error_msg'] = msg
                return render(request, 'registration/login.html', context) 
                      
    return return_file


# @login_required
# @permission_required('runo.is_teacher')
# @permission_required('runo.is_pupil')

all_classes = [('1', 'Pre-Nursery'), ('2', 'Nursery 1'), ('3', 'Nursery 2'), ('4', 'Nursery 3'),
               ('5', 'Basic 1'), ('6', 'Basic 2'), ('7', 'Basic 3'), ('8', 'Basic 4'),
               ('9', 'Basic 5'), ('10', 'Basic 6')]

from django.core.paginator import PageNotAnInteger, Paginator, EmptyPage

@permission_required('runo.is_teacher')
def teacher(request):
    
    
    try:
        aboutSchool = FooterDetails.objects.all().order_by('-id')[0] 
    except:
        aboutSchool = None
    try:
        Class = request.user.userclass_set.first().Class
        #return HttpResponse(Class)
        class_name = all_classes[int(Class) -1][1]
        

runo/templates/runo/sms/adminMessage.html
{%  extends "runobase.html" %}

{% block body %}
{% if message %}


{{message.title}}
{{message.message}}
{% endif %}

{% endblock %}

runo/templates/runo/sms/class.html
{% extends 'runobase.html' %}

{% block body %}
<div id='aboutStudents'>
    
    <style>
        #studentDetailsHouse{
            margin: auto;
            margin-top: 20px;
            margin-bottom: 20px;
            width: 90%;
            
            padding: 18px;
            border-radius: 25px;
            box-shadow: 0px 0px 15px 0px black;
            display: flex;
            flex-wrap: wrap;
            justify-content: space-evenly;
            align-items: center;
            
            
        }
        #studentDetailsHouse span{
            padding: 10px;
            padding-left: 30px;
            padding-right: 30px;
            color: white;
            background-color: orangered;
            border-radius: 20px;
            font-weight: bolder;
            margin-bottom: 20px;
            box-shadow: 0px 0px 10px 0px orangered;
        }
        @media screen and (max-width: 1361px){
            #studentDetailsHouse table{
            width: 100%;
            }
            
        }
        @media screen and (min-width: 1361px){
            #studentDetailsHouse table{
            width: 60%;
            }
            
        }
        

        tr{
            width: 100%;
            text-align: start;  
        
            
        }
        th{
            text-align: center;
          
        }

        th, td{
            text-align: start;
            
            padding: 15px;
        }
        td{
            text-align: start;
            padding: 6px;
            transition: padding-top 0.3s ease;
            transition: padding-bottom 0.3s ease;

        }
        tr:hover{
            box-shadow: 0px 0px 5px 0px black;
            border-radius: 5px;
            
        }
        td:hover{
            padding-top: 25px;
             padding-bottom: 25px; 
        }
        
        .pupilsBody:hover{
            border-left: 5px solid yellowgreen;
        }
       
        #pupilsHead{
            border-left: 5px solid rgb(1, 1, 69);
            border-radius: 3px;
            
        }
        .pupilsBody{
            border-left: 5px solid orangered;
            border-radius: 3px;
        }
        .pupilsBody a{
            text-decoration: none;
            color: navy;
        }
        .night .pupilsBody a, .colorful .pupilsBody a{
            text-decoration: none;
            color: lightgoldenrodyellow;
        }
        tr:nth-child(even){
            background-color: aliceblue;
            border-left: 5px solid green;
        }
        .night tr:nth-child(even){
            background-color: rgb(36, 35, 35);
        }
        .colorful tr:nth-child(even){
            background-color: rgb(10, 157, 157);
        }
        

    </style>
    <div id='studentDetailsHouse'>
        <span>{{ class_name }}</span>
        

    
<table>
    <thead>
        <tr>
            <th id='pupilsHead'>
                PUPILS
            </th>
            <th>
                CLASS
            </th>
            <th>
                ClASS TEACHER
            </th>
        </tr>
    </thead>

    <tbody>
        {% for classPupil in Users %}
        
            <tr>
                    <td class='pupilsBody'>
                        <a href='{% url "runo:result" Class classPupil.users.first.username %}'>
                        {{ classPupil.users.first.username }}  
                        {{ classPupil.users.first.first_name }}  
                        {{ classPupil.users.first.last_name }}  
                        </a>
                    </td>  
                        

                    <td>
                        {{ class_name }}
                    </td>
                    <td>
                        {{ request.user.username }}
                    </td>
            </tr>

        {% empty %}
        <tr>
            <td class='pupilsBody'>
                No pupil yet
            </td>  
            <td>
                {{ class_name }}
            </td>
            <td>
                {{ request.user.username }}
            </td>
        </tr>
        {% endfor %}
    </tbody>
    
</table>
{% block content %}
        {% include 'runo/paginator.html' with page=Users %}

        <style>
            #logoutButton{
                padding: 10px;
                background-color: rgb(2, 40, 70);
                border: 1px solid rgb(210, 223, 234);
                border-radius: 3px; 
                border: 1px solid rgb(2, 40, 70)

            }
            #logoutButton a{
                color: white;
                text-decoration: none;
            }
        </style>
        <button id='logoutButton'><a href='{% url "runo:logout" %}'>Logout</a></button>
    {% endblock %}
</div>
</div>
{% endblock %}  

runo/templates/runo/sms/editProfile.html
{% extends 'runobase.html' %}

{% block body %}
<div class='statusContainer'>
    <div id='currentProfile'>
        <style>
            .statusContainer{
                margin: auto;
            }

            #currentProfile{
                position: relative;
                text-align: center;
                /* color: black; */
            }
            .bottom-right {
                position: absolute;
                bottom: 42px;
                right: 42px;
                color: white;
                }

            .night .bottom-right{
                color: black;
            }
            .colorful .bottom-right{
                color: teal;
            }
            
            #currentProfile img{
                background-image: linear-gradient(aliceblue, rgb(0, 10, 60));
                width: 100%;
                /* min-height: 200px; */
                border-bottom-right-radius: 30px;;
            }
            @media screen and (max-width: 900px){
                .statusContainer{
                width: 100%;
            }

            }
            @media screen and (min-width: 1000px){
                .statusContainer{
                width: 50%;
            }

            }
            .noImg{
                min-height: 250px;
            }

        </style>
        {% if request.user.userprofile.profile_image %}
            <img src='{{ request.user.userprofile.profile_image.url }}' alt='{{ request.user.username }}'>
        {% else %}
            <img class='noImg'>
        {% endif %}
        <div class="bottom-right">
            {{ request.user.username }}
            &#x2764;
        </div>
        <div id='status'>
            {% if request.user.userprofile.status %}
                {{ request.user.userprofile.status }}

            {% else %}
                No status yet
            {% endif %}
        </div>
    </div>

    {% if user_profile %}
    <style>
        #updateProfile{
            margin-top: 30px;
            padding: 20px;
            background: rgba(255, 255, 255, 0.25);
            box-shadow: 0px 8px 32px 0 rgba(31, 38, 135, 0.37);

            backdrop-filter: blur(4px);
                -webkit-backdrop-filter: blur(4px);
            border-radius: 10px;
            border: 1px solid rgba(255, 255, 255, 0.18);
            margin-bottom: 30px;
        }
        .night #updateProfile{
            box-shadow: 0px 8px 32px 0px black;
        }
        form p{
            padding-bottom: 10px;
        }
        input[type='file']{
            background-color: rgba(0,0,0, 0.86);
            margin-top: 10px;
            padding: 5px;
        }
        form input[type=text]{
            border: 0px solid white;
            width: 100%;
            min-height: 40px;
            padding-left: 10px;
            border-bottom: 3px solid rgba(5, 5, 5, 0.7);
        }
        form button{
            background-color: navy;
            padding: 12px;
            color: white;
            border: 1px solid navy;
            border-radius: 3px;
        }
        form{
           
            padding: 10px;
            padding-top: 3px;
            border-radius: 4px;
        }
        .staticData{
            margin: 20px;
            margin-left: 30px;

            border-bottom: 1px solid rgb(213, 211, 211);
        }
        form:hover{
            box-shadow: 0px 1px 12px 0px black;
        }
        .night form input[type=text]{
            border: 0px solid white;
            width: 100%;
            color: white;
            background-color: black;
            border-bottom: 3px solid rgba(167, 165, 165, 0.5);
        }
        
    </style>

<div class='staticData'>
    Username: {{ request.user.username }}
</div>

    <div class='staticData'>
        Name: {{ request.user.first_name }} {{ request.user.last_name }}
    </div>

    <div class='staticData'>
        Current Class: {{ current_class }}
    </div>
    <div class='staticData'>
        Email Address: {{ request.user.email }}
    </div>
    <div id='updateProfile'>
        <h3 style='text-align: center;'>Update Profile</h3>
        <form enctype="multipart/form-data" method='post'>
            {% csrf_token %}
            {{ user_profile.as_p }}
            <button>Update Profile</button>
        </form>
        <style>
            #password-change{
                background-color: rgb(14, 14, 14);
                border: 1px solid rgb(14, 14, 14);
                padding: 10px;
                display: inline-flex;
                border-radius: 10px;
                box-shadow: 0px 4px 16px 0px black;
                
            }
            #password-change a{
                text-decoration: none;
                color: white;
            }
        </style>
        <h3 id='password-change'><a href='{% url "runo:change_password" %}'>Change Password</a></h3>
    </div>
    {% endif %}

</div>
{% endblock %}

runo/templates/runo/sms/resultForPupil.html
{% extends 'runobase.html' %}
{% block body %}
    <div id='Results'>
        <style>
            #Results{
                display: flex;
                /* flex-wrap: wrap; */
                justify-content: center;
                margin: auto;
                margin-top: 20px;
                margin-bottom: 20px;
                color: white;

            }
            @media screen and (max-width: 1361px){
                #Results{
                    width: 95%;
                }
            }
            @media screen and (min-width: 1361px){
                #Results{
                    width: 70%;
                }
            }
            .AllResults, .result{
                background-color: black;
                padding: 12px;
            }
            #Results:hover{
                box-shadow: 1px 1px 18px 1px black;
            }
            .AllResults{
                width: 35%;
                border-radius: 4px;
                border-top-right-radius: 10px;
                border-bottom-right-radius: 10px;
                text-align: center;
            }
            .result{
                width: 65%;
                border-radius: 4px;;
                border-top-left-radius: 10px;
                border-bottom-left-radius: 10px;
                display: flex;
                align-items: center;
                justify-content: center;
            }
            .AllResults a{
                text-decoration: none;
                color: white;
            }
            .AllResults a > div{
                /* width: 90%; */
                margin: auto;
                background-color: rgb(0, 0, 24);
                text-decoration: none;
                color: white;
                padding: 10px;
                margin-bottom: 10px;
            }
            .AllResults a > #currentClass{
                background-color: teal;
            }
        </style>
        <div class='AllResults'>
            <div id='userProfile'>
                <style>
                    #userImg{
                        width: 99%;
                        border: 0px;

                    }
                    #userImg{
                        width: 100%;
                        background-size: cover;
                        background-position: center;
                    }
                    #userImg .userImg{
                        /* background-image: linear-gradient(white, rgb(0, 0, 41)); */
                        background: linear-gradient(110deg, navy 60%, darkblue 60%);
                        display: block;
                        /* width: 99%; */
                        height: 100px;
                        width: 100px;
                        object-fit: cover;
                        border-radius: 50%;;
                        margin: auto;
                        border: 2px solid white;
                       
                    }
                </style>
                <div id='userImg'>
                    {% if request.user.userprofile.profile_image %}
                        <img class='userImg' src='{{ request.user.userprofile.profile_image.url }}' /> 
                        <p>{{ request.user.username }}</p>
                        <br>

                   {% else %}
                        <img class='userImg'>
                        <p>{{ request.user.username }}</p>
                    <br>
                    {% endif %}
                </div>
            </div>

        {% for result in results %}
            {% if result.Class == Class %}
                <a class='classResult' href='{% url "runo:viewResults" result.Class %}'>
                    
                    <div id='currentClass'>
                        <svg width="21" height="21" viewBox="0 0 42 42" fill="none">
                            <path d="M20.8994 11.5527L30.4472 21L20.8994 30.5477" stroke="#23233C" stroke-width="2" stroke-linecap="round"/>
                            <path d="M30.4471 21H11.4521" stroke="#23233C" stroke-width="2" stroke-linecap="round"/>
                            <path d="M41 21C41 32.0553 32.0553 41 21 41C9.94472 41 1 32.0553 1 21C1 9.94472 9.84422 1 20.8995 1C31.9548 1 41 9.94472 41 21Z" stroke="#23233C" stroke-width="2" stroke-linecap="round"/>
                        </svg>
                        {{ result.className }} Results</div>
                </a>
                <br>
            {% else %}
            <a class='classResult' href='{% url "runo:viewResults" result.Class %}'>
                    
                    <div>
                        <svg width="21" height="21" viewBox="0 0 42 42" fill="none">
                            <path d="M20.8994 11.5527L30.4472 21L20.8994 30.5477" stroke="#23233C" stroke-width="2" stroke-linecap="round"/>
                            <path d="M30.4471 21H11.4521" stroke="#23233C" stroke-width="2" stroke-linecap="round"/>
                            <path d="M41 21C41 32.0553 32.0553 41 21 41C9.94472 41 1 32.0553 1 21C1 9.94472 9.84422 1 20.8995 1C31.9548 1 41 9.94472 41 21Z" stroke="#23233C" stroke-width="2" stroke-linecap="round"/>
                            </svg>
                        {{ result.className }} Results</div>
                </a>
                <br>
            {% endif %}

        {% empty %}
            <div class='classResult'>
                No recorded result
            </div>
        {% endfor %}
        </div>

        <div class='result'>
            
            <div>
                <style>
                    .viewResult{
                        background-color: yellowgreen;
                        color: white;
                        border: 1px solid yellowgreen;
                        padding: 10px;
                        margin: 10px;
                        cursor: pointer;
                        border-radius: 3px;
                        
                    }

                    .noResult{
                        background-color: maroon;
                        color: white;
                        border: 1px solid maroon;
                        padding: 10px;
                        margin: 10px;
                        border-radius: 3px;
                    }
                </style>
                {% if res_in_view %}
                <h2>Result for {{ res_in_view.className }}</h2> 

                    {% if res_in_view.first_term %}
                        <a href='{{ res_in_view.first_term }}' target='_blank'>
                            <button class='viewResult'>View First Term Result</button>
                        </a>
                    {%else%}
                        <button class='noResult'>No result For first Term</button>
                    {% endif %}

                    {% if res_in_view.second_term %}
                        <a href='{{ res_in_view.second_term }}' target='_blank'>
                            <button class='viewResult'>View Second Term Result</button>
                        </a>
                    {%else%}
                        <button class='noResult'>No result For Second Term</button>
                    {% endif %}

                    {% if res_in_view.third_term %}
                        <a href='{{ res_in_view.third_term }}' target='_blank'>
                            <button class='viewResult'>View Third Term Result</button>
                        </a>
                    {%else%}
                        <button class='noResult'>No result For Third Term</button>
                    {% endif %}


                {% else %}
                <button class='noResult'>No result uploaded for this class</button>
                {% endif %}
            </div>
        </div>

    </div>
{% endblock %}