runo/urls.py
from . import views
from django.urls import path, include

app_name = 'runo'
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('', views.index, name='index'),
   # path('searchBase/', views.searchBase, name='searchBase'),
    path('news/<str:slug>/<int:year>/<int:month>/<int:day>/', views.news, name='news'),
    path('gallery/', views.gallery, name='gallery'),
    path('about/', views.aboutUs, name='about'),
    path('academics/', views.academics, name='academics'),
    
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('password_change/', views.change_password, name='change_password'),
    
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    
    path('register/', views.register, name='register'),
    path('teacher/', views.teacher, name='teacher'),
    path('result_page/<str:Class>/<str:username>/', views.result_page, name='result_page'),
    path('result/<str:Class>/<str:username>/', views.result, name='result'),
    path('changeclass/<str:Class>/<str:username>/<str:status>', views.changeclass, name='changeclass' ),
    path('pupil/', views.pupil, name='pupil'),
    path('updateProfile/', views.updateProfile, name='updateProfile'),
    path('sendMsg/', views.sendMsg, name='sendMsg'),
    path('viewResults/<str:Class>/', views.viewResults, name='viewResults'),
    
    path('msg_for_admin/<int:id>/', views.msg_for_admin, name='msg_for_admin'),
    path('admin_msgs/', views.msg_for_admin2, name='msg_for_admin2'),
    path('admin_update_user/<str:username>/', views.admin_update_user, name='admin_update_user'),
    
    path('adminPanel/', views.adminPanel, name='adminPanel'),
    path('message_all_users/', views.message_all_users, name='message_all_users'),
    path('viewSchoolMessage/', views.viewSchoolMessage, name='viewSchoolMessage')
    
]

runoschool/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('runo.urls', namespace='runo')),
    # path('', include('django.contrib.auth.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

runo/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import UserClass, UserProfile

class Register(forms.ModelForm):
    classifier = [('not_sure', 'not sure'), ('is_student', 'Student'), ('is_teacher', 'Teacher')]
    class Meta:
        model = User
        fields = ['username', 'email', 'first_name', 'last_name']
        
        
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Retype Password', widget=forms.PasswordInput)
    usertype = forms.ChoiceField(choices=classifier)
    
    def verify_password(self):
        password1 = self.cleaned_data['password1']
        password2 = self.cleaned_data['password2']
        if len(password1) < 6 or len(password2) < 6:
            raise forms.ValidationError('Password must be at least six characters long')
            return None
        
        elif password1 != password2:
            raise forms.ValidationError('Passwords do not match')
            return None
        
        else:
            return self.password1
    
class UserClassName(forms.Form):
    classes = [('1', 'Pre-Nursery'), ('2', 'Nursery 1'), ('3', 'Nursery 2'), ('4', 'Nursery 3'),
               ('5', 'Basic 1'), ('6', 'Basic 2'), ('7', 'Basic 3'), ('8', 'Basic 4'),
               ('9', 'Basic 5'), ('10', 'Basic 6')]
    Class = forms.ChoiceField(choices=classes)
    
class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ['profile_image', 'status']    
    

runo/views.py
from django.shortcuts import render, reverse
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.shortcuts import get_object_or_404
import datetime
from django.core.mail import send_mail

from .models import Intro, News, ImportantDates, FooterDetails, Gallery, AboutSchool, Academics, UserClass, Result, AllResults
from .models import UserProfile, Message
from .forms import UserClassName, UserProfileForm
from django.db.models import Q

# Create your views here.

#def searchBase(request):
    
        
        
def index(request):
    introImgs = Intro.objects.all().order_by('-uploaded')[:1]
    news = News.objects.filter(publish=True).order_by('-published').all()[:6]
    dates = ImportantDates.objects.filter(date__gte=datetime.date.today()).order_by('date')[:12]
    
    try:
        aboutSchool = FooterDetails.objects.all().order_by('-id')[0] 
    except:
        aboutSchool = None
    
    allNews = None
    if request.method == 'POST':
        searchData = request.POST['searchData']
        newsSearch = News.objects.filter(Q(title__icontains=searchData) | Q(newsBody__icontains=searchData) | Q(desc__icontains=searchData)).all() 
        events = ImportantDates.objects.filter(event__icontains=searchData).all()
        
        allNews = newsSearch
    
    
    # Show upcoming events 14 days prior
    upcoming_event = None
    if len(dates) > 0:
        closest_event = 100000
        for upcoming in dates:
            
            time = ( datetime.date(upcoming.date.year, upcoming.date.month, upcoming.date.day) - datetime.date.today()).days
            if time < closest_event and time > -1:
                closest_event = time
            if time < 14 and time <= closest_event and time > -1:
                upcoming_event = {'upcoming': upcoming, 'time': time }
            
    if len(introImgs) > 0:
        introImg = []
        for intro in introImgs:
            details = {
                'img': intro.img.url,
                'schoolName': intro.schoolName,
                'desc': intro.desc
            }
            introImg.append(details)
            
        return render(request, 'runo/index.html', {'section': 'home', 'allNews': allNews,
                                                   'introImg': introImg,
                                                   'news': news, 'upcoming_event': upcoming_event,
                                                   'dates': dates, 'aboutSchool': aboutSchool})

    return render(request, 'runo/index.html', {'section': 'home', 'news': news, 'allNews': allNews,
                                               'upcoming_event': upcoming_event,
                                               'dates': dates, 'aboutSchool': aboutSchool})


def news(request, slug, year, month, day):
    newsItem = News.objects.filter(slug=slug, published__day=day,
                                 published__month=month, published__year=year).first()
    
    news = News.objects.filter(publish=True).order_by('-published').all()[:6]
    try:
        aboutSchool = FooterDetails.objects.all().order_by('-id')[0] 
    except:
        aboutSchool = None
    return render(request, 'runo/news.html', {'aboutSchool': aboutSchool, 'newsItem': newsItem, 'news': news})


def gallery(request):
    gallery = Gallery.objects.filter(display=True).order_by('-uploaded').all()
    try:
        aboutSchool = FooterDetails.objects.all().order_by('-id')[0] 
    except:
        aboutSchool = None
    return render(request, 'runo/gallery.html', {'galleries': gallery, 'aboutSchool': aboutSchool})



def aboutUs(request):
    newsItem = AboutSchool.objects.filter(publish=True).order_by('-published').first()
    news = News.objects.filter(publish=True).order_by('-published').all()[:6]
    try:
        aboutSchool = FooterDetails.objects.all().order_by('-id')[0] 
    except:
        aboutSchool = None
    return render(request, 'runo/about.html', {'aboutSchool': aboutSchool, 'newsItem': newsItem, 'news': news, 'section': 'about'})

from django.contrib.auth.models import Group, Permission
from django.contrib.auth.decorators import login_required, permission_required


def academics(request):
    newsItem = Academics.objects.order_by('-published').first()
    news = News.objects.filter(publish=True).order_by('-published').all()[:6]
    try:
        aboutSchool = FooterDetails.objects.all().order_by('-id')[0] 
    except:
        aboutSchool = None
    
    return render(request, 'runo/about.html', {'aboutSchool': aboutSchool, 'newsItem': newsItem, 'news': news, 'section': 'academics'})



# Student Management System
from .models import Users
from django.contrib.auth.models import Group, Permission
from django.contrib.contenttypes.models import ContentType
from django.contrib.auth.models import User
from .forms import Register


teacher_group = None
pupil_group = None

# teacher_group, created = Group.objects.get_or_create(name='teacher_group')
# ct = ContentType.objects.get_for_model(Users)
                
# permission = Permission.objects.filter(codename='is_teacher', name='is_teacher', content_type=ct).first()
# teacher_group.permissions.add(permission)


# pupil_group, created = Group.objects.get_or_create(name='pupil_group')
# Content_type = ContentType.objects.get_for_model(Users)
# pupil_permission = Permission.objects.filter(codename='is_pupil', name='is_pupil', content_type=Content_type).first()
# pupil_group.permissions.add(pupil_permission)

#@staff_member_required
def register(request):
    form = Register()
    form2 = UserClassName()
    try:
        aboutSchool = FooterDetails.objects.all().order_by('-id')[0] 
    except:
        aboutSchool = None
    context = {'form': form, 'form2': form2, 'section': 'register', 'aboutSchool': aboutSchool}
    return_file = render(request, 'registration/login.html', context)
    if request.method == 'POST':
        form = Register(request.POST)
        form2 = UserClassName(data=request.POST)
        if form.is_valid() and form2.is_valid():
            password1 = form.cleaned_data['password1']
            password2 = form.cleaned_data['password2']
            email = form.cleaned_data['email']
            used_email = User.objects.filter(email=email).first()
            user_type = form.cleaned_data['usertype']
            user_class = form2.cleaned_data['Class']
            
            if used_email:
                context['error_msg'] = 'Email address already in use'
                return render(request, 'registration/login.html', context)
                
            if password1 != password2:
                context['error_msg'] = 'Passwords do not match'
                return render(request, 'registration/login.html', context)
            elif len(password1) < 6:
                context['error_msg'] = 'password must be at least six characters long'
                return render(request, 'registration/login.html', context)
            
            else:
                new_user = form.save(commit=False)
                new_user.set_password(password1)
                
                new_user.save()
                
                
                
                
                if user_type == 'is_teacher':
                    class_for_user = UserClass(Class=user_class, is_student=False, is_teacher=True)
                    class_for_user.save()
                    class_for_user.users.add(new_user)
                    class_for_user.save()
                    new_user.groups.add(teacher_group)
                    
                    new_user_profile = UserProfile(user=new_user)
                    new_user_profile.save()
                    
                    msg = 'User registered as teacher'
                    
                elif user_type == 'is_student':
                    
                    class_for_user = UserClass(Class=user_class, is_student=True)
                    class_for_user.save()
                    class_for_user.users.add(new_user)
                    class_for_user.save()
                    result = Result(user=new_user, current_class=user_class)
                    result.save()
                
                    new_user.groups.add(pupil_group)
                    
                    new_user_profile = UserProfile(user=new_user)
                    new_user_profile.save()
                    
                    msg = 'User registered as pupil'
                    
                elif user_type == 'not_sure':
                    class_for_user = UserClass(Class=user_class, is_student=False)
                    class_for_user.save()
                    class_for_user.users.add(new_user)
                    class_for_user.save()
                    
                    new_user_profile = UserProfile(user=new_user)
                    new_user_profile.save()
                    
                    msg = 'User saved, but has not ben assigned a role'
                    
                    
                
                context['error_msg'] = msg
                return render(request, 'registration/login.html', context) 
                      
    return return_file


# @login_required
# @permission_required('runo.is_teacher')
# @permission_required('runo.is_pupil')

all_classes = [('1', 'Pre-Nursery'), ('2', 'Nursery 1'), ('3', 'Nursery 2'), ('4', 'Nursery 3'),
               ('5', 'Basic 1'), ('6', 'Basic 2'), ('7', 'Basic 3'), ('8', 'Basic 4'),
               ('9', 'Basic 5'), ('10', 'Basic 6')]

from django.core.paginator import PageNotAnInteger, Paginator, EmptyPage

@permission_required('runo.is_teacher')
def teacher(request):
    
    
    try:
        aboutSchool = FooterDetails.objects.all().order_by('-id')[0] 
    except:
        aboutSchool = None
    try:
        Class = request.user.userclass_set.first().Class
        #return HttpResponse(Class)
        class_name = all_classes[int(Class) -1][1]
        

runo/templates/runo/about.html
{% extends 'runobase.html' %}


{% block body %}

{% if newsItem %}
    <div id='targetNews'>
        <style>
            #targetNews{
                margin: auto;
                margin-top: 30px;
            }
            @media screen and (max-width: 1361px){
                #targetNews{
                    width: 85%;
                }
            }
            @media screen and (min-width: 1361px){
                #targetNews{
                    width: 50%;
                }
            }
            #targetNews #newsHeader{
            padding-right: 20px;
            }
            #targetNews #newsHeader a{
                display: flex;
                align-items: center;
                justify-content: center;
                text-decoration: none;
                color: white;
                background-color: grey;
                width: 50px;
                height: 50px;
                border-radius: 50%;;
            }
            #targetNews #newsHeader > section{
                display: flex;
                flex-wrap: wrap;
                margin-top: 30px;
                margin-bottom: 30px;;
            }

            #targetNews #newsHeader #img{
                width: 90px;
            }
            #targetNews #newsHeader #img img{
                width: 75px;
                height: 75px;
                border-radius: 50%;       
            }
            #targetNews #targetNewsImg{
                width: 100%;   
                padding-top: 15px;
                padding-bottom: 25px;
            }
            #targetNews #targetNewsImg img{
                width: 100%;   
            }
            #targetNews #targetNewsImg p{
                width: 100%;   
                text-align: center;
                color: rgb(63, 63, 63)
            }
            .night #targetNews #targetNewsImg p{
                color: rgb(245, 240, 240)
            }
            #targetNews #newsBody{
                margin-bottom: 35px;
                margin-top: 10px;
            }
        </style>

        
        <div id='newsHeader'>
            <h1>{{ newsItem.title }}</h1>
            <br>
            <span><a href='#MarS'>down</a></span>
            
            <section>
                <div id='img'>
                    <img src='{{ newsItem.img.url }}' alt='{{newsItem.desc}}'>
                </div>
                <section style='margin-top: 25px;'>
                    {% if aboutSchool %}
                        {{ aboutSchool.school_name }}
                    {% else %}
                        School name from footer will appear here
                    {% endif %}
                    <br>
                    {{ newsItem.published }}
                </section>
            </section>
        </div>

        <div id='targetNewsImg'>
            <img src='{{ newsItem.img.url }}' alt='{{newsItem.desc}}'>
            <p>{{ newsItem.desc }}</p>
        </div>

        <div id='newsBody'>
            {{ newsItem.aboutBody | safe | linebreaks}}
        </div>

    </div>
{% endif %}



<div id='news'>
    <style>
        #news{
            padding: 15px;
            display: flex;
            flex-wrap: wrap;
            justify-content: space-between;
        }
        #news h1{
            border-bottom: 4px solid black;
            width: 100%;

        }
        .night #news > h1, .colorful #news > h1{
            border-bottom: 4px solid white;
        }

        #news a{
            text-decoration: none;
        }

        #news a{
            color: black;
        }

        .night #news a, .colorful #news a{
            color: white;
        }
        
        #news .news{
                display: flex;
                flex-wrap: wrap;
                justify-content: space-between;
                margin-bottom: 15px;
                margin-top: 25px;
            }

        #news .news > .newsDesc{
                width: 65%;
            }
            .news > .newsDesc h2, .news > .newsDesc p{
                padding-bottom: 10px; 
            }
            .news > .newsImg{
                width: 25%;
            }

            .newsImg > img{
                width: 100%;
            }
            #news a{
                margin-top: 20px;
                margin-bottom: 20px;
                /* box-shadow: 0px 1px 5px 0px black; */
                padding: 15px; 
            }
            #news a:hover{
                box-shadow: 1px 1px 20px 3px black;
            }
        @media screen and (max-width: 1361px){
            #news a{
                width: 99%;
            }
        }

        @media screen and (min-width: 1361px){
            #news a{
                width: 45%;
            }
        }


    </style>
    
    {% if news %}
        <h1>NEWS FROM RUNO</h1>
        {% for newsArticle in news %}
            <a href='{{ newsArticle.get_absolute_url }}'>  
                <div  class='news'>
                    <div class='newsDesc'>
                        <h2>
                            {{ newsArticle.title }}
                        </h2>
                        <p>{{ newsArticle.desc }}</p>
                        <p>{{ newsArticle.newsBody | truncatewords:15 | linebreaks}}</p>

                    </div>

                    <div class='newsImg'>
                        <img src='{{ newsArticle.img.url }}'>
                    </div>
                </div>
            </a>
        {% empty %}
            Nothing here yet
        {% endfor %}
    {% endif %}
</div>


{% endblock %}

runo/templates/runo/index.html
{% extends 'runobase.html' %}

{% block body %}
<div id='intro'>
    <style>
        #intro{
            display: flex;
            flex-wrap: wrap;
            background-color: rgb(96, 116, 67);
            margin-bottom: 15px;
            background: rgba(255, 255, 255, 0.25);
            box-shadow: 0px 8px 32px 0 rgba(31, 38, 135, 0.37);

            backdrop-filter: blur(4px);
                -webkit-backdrop-filter: blur(4px);
            border-radius: 10px;
            border: 1px solid rgba(255, 255, 255, 0.18);
        }
        #intro:hover{
            box-shadow: 1px 1px 15px 1px rgb(8, 14, 0);
        }
        .night #intro{
            box-shadow: 0px 8px 32px 0px black;;
        }
        @media screen and (min-width: 1361px){
            
            .introImg{
                width: 50%;
            }
            .schoolName{
                width: 50%;
                height: 100%;
            }
            .introImg img{
                width: 100%;
            }

        }
        @media screen and (max-width: 1361px){

            .schoolName{
                padding-top: 100px;
                padding-bottom: 100px;
            }

            .introImg{
                width: 100%;
            }
            .schoolName{
                width: 100%;
            }
            .introImg img{
                width: 100%;
            }

        }

        #intro{
            margin-top: 20px;
        }
        .schoolName{
            
            
            color: black;
            text-align: center;
            margin: auto;
        }
        .schoolName #inBold{
            font-size: xx-large;
            padding-bottom: 5px;
            text-align: center;
        }

        .night .schoolName{
            color: white;
        }
    </style>
    {% if introImg %}
        {% for introImg in introImg %}
        <div  class='introImg'>
            <img src='{{ introImg.img }}' alt='{{ introImg.schoolName}}'>
        </div>
        <div class='schoolName'>
            <p id='inBold'>{{ introImg.schoolName }}</p>
            <p>{{ introImg.desc | linebreaks }}</p>
        </div>
        {% endfor %}

    {% else %}

        
        <div class='schoolName'>
            <p id='inBold'>RUNO DAYSPRING SCHOOL</p>
            <p>Additional text should follow right under</p>
        </div>
    {% endif %}

</div>


<div id='otherInfo'>

    <style>
        #otherInfo{
            margin-top: 25px;
            margin-bottom: 25px;
            display: flex;
            flex-wrap: wrap;
            padding-top: 25px;
            padding-bottom: 25px;
            justify-content: center;
        }
        #otherInfo:hover{
            box-shadow: 1px 1px 15px 1px rgb(8, 14, 0);
        }

        #otherInfo > div{
            text-align: center;
            background-color: rgb(0, 35, 57);
            color: white;
            font-size: x-large;
            padding-top: 18px;
            padding-bottom: 18px;
            margin-bottom: 18px;
            cursor: pointer;
        }

        @media screen and (max-width: 1361px){
            #otherInfo > div{
                width: 60%;
            }
        }

        #otherInfo > div:hover{
            box-shadow: 1px 1px 15px 1px rgb(8, 14, 0);
        }
        #otherInfo a{
            text-decoration: none;
            color: white;
    
            /* text-shadow: 1px 1px 4px rgb(6, 14, 0); */
        }
        @media screen and (min-width: 1361px){
            #otherInfo{
                justify-content: space-evenly;
                margin-top: 40px;
                margin-bottom: 40px;
            }
            #otherInfo > div{
                width: 30%;
            }
        }

    </style>
    <div>
        <a href='#dates'>Calender</a>
    </div>

    <div>
        <a href='{% url "runo:gallery" %}'>Gallery</a>
    </div>

    <div>
        <a href='#footerSchoolDetails'>Contact</a>
    </div>

</div>



<div id='news'>
    <style>
        #news{
            padding: 15px;
            display: flex;
            flex-wrap: wrap;
            justify-content: space-between;
        }
        #news h1{
            border-bottom: 4px solid black;
            width: 100%;

        }
        .night #news > h1, .colorful #news > h1{
            border-bottom: 4px solid white;
        }

        #news a{
            text-decoration: none;
        }

        #news a{
            color: black;
        }

        .night #news a, .colorful #news a{
            color: white;
        }
        
        #news .news{
                display: flex;
                flex-wrap: wrap;
                justify-content: space-between;
                margin-bottom: 15px;
                margin-top: 25px;
            }

        #news .news > .newsDesc{
                width: 65%;
            }
            .news > .newsDesc h2, .news > .newsDesc p{
                padding-bottom: 10px; 
            }
            .news > .newsImg{
                width: 25%;
            }

            .newsImg > img{
                width: 100%;
            }
            #news a{
                margin-top: 20px;
                margin-bottom: 20px;
                /* box-shadow: 0px 1px 5px 0px black; */
                padding: 15px; 
            }
            #news a:hover{
                box-shadow: 1px 1px 20px 3px black;
            }
        @media screen and (max-width: 1361px){
            #news a{
                width: 99%;
            }
        }

        @media screen and (min-width: 1361px){
            #news a{
                width: 45%;
            }
        }


    </style>
    <h1>NEWS AND ANNOUNCEMENTS</h1>
    {% if news %}
        {% for newsArticle in news %}
            <a href='{{ newsArticle.get_absolute_url }}'>  
                <div  class='news'>
                    <div class='newsDesc'>
                        <h2>
                            {{ newsArticle.title }}
                        </h2>
                        <p>{{ newsArticle.desc }}</p>
                        <p>{{ newsArticle.newsBody | truncatewords:15 | linebreaks}}</p>

                    </div>

                    <div class='newsImg'>
                        <img src='{{ newsArticle.img.url }}'>
                    </div>
                </div>
            </a>
        {% empty %}
            Nothing here yet
        {% endfor %}
    {% endif %}
</div>


<div id='dates'>
    <style>
        #dates{
            display: flex;
            flex-wrap: wrap;
            justify-content: center;
        }
        #dates h1{
            border-bottom: 4px solid black;
            width: 100%;
        }
        #dates h2{
            text-align: center;
            width: 100%;
        }
        .night #dates > h1, .colorful #dates > h1{
            border-bottom: 4px solid white;
        }

        #dates #upcomingEvent{
            display: flex;
            flex-wrap: wrap;
            margin-top: 25px;
            border-radius: 20px;
            box-shadow: 1px 1px 12px 1px rgb(8, 14, 0);
            margin-bottom: 30px;
        }
        #upcomingEvent #design{
                width: 40%;
                padding-top: 70px;
                padding-bottom: 70px;
                background-color: rgb(0, 35, 57);
                display: flex;
                justify-content: center;
                align-items: center;
                color: white;
                font-size: x-large;
            }
            #upcomingEvent #event{
                width: 60%;
                display: flex;
                flex-wrap: wrap;
                font-size: x-large;
                justify-content: space-around;
            }
            #upcomingEvent #event > span{
                width: 80%;
                margin: auto;
                text-align: center;
            }
        @media screen and (min-width: 1361px) {
            #dates #upcomingEvent{
                     width: 60%;
                     }
                    
        }
        @media screen and (max-width: 1361px) {
            #dates #upcomingEvent{
                width: 90%;
            }
        }

    </style>
    <h1> UPCOMING EVENTS</h1>
    {% if upcoming_event %}

        <div id='upcomingEvent'>
            <div id='design'>UPCOMING EVENT</div>
            <div id='event'>
                <span>{{ upcoming_event.upcoming.date }}</span>
                <span>
                    {% if upcoming_event.time == 0 %}
                        Happening today {{upcoming_event.upcoming.event }}
                    {% else %}
                        {{ upcoming_event.time }} days to {{upcoming_event.upcoming.event}}
                    {% endif %}
                </span>
            </div>
        </div>
     {% else %}
        <div id='upcomingEvent'>
            <div id='design'>UPCOMING EVENT</div>
            <div id='event'><span>No upcoming event</span></div>
        </div>
    {% endif %}
    <style>
        #eventDates{
            display: flex;
            flex-flow: wrap;
            justify-content: center;
        }
        #eventDates div > h2{
                color: rgb(1, 1, 55);
                padding-bottom: 10px;
                border-bottom: 2px solid rgb(1, 1, 75);
            }
        
        .night #eventDates div > h2{
                color: rgb(236, 236, 244);
                padding-bottom: 10px;
                border-bottom: 2px solid rgb(234, 234, 242);
            }

            #eventDates div > h2, #eventDates div > h3 {
                padding-top: 15px;
                display: flex;
                flex-wrap: wrap;
            }
        @media screen and (max-width: 1361px){
            #eventDates > div{
                width: 30%;
                margin: 10px;
            }
            
        }

        @media screen and (min-width: 1361px){
            #eventDates > div{
                width: 20%;
                margin: 18px;
            }
            
        }
        

    </style>

    <h2>IMPORTANT DATES</h2>
    <div id='eventDates'>
        {% if dates %}
        
            {% for date in dates %}
            <div>
                <h2>{{date.date}}</h2>
                <h3>{{ date.event }}</h3>
            </div>
            
            {% empty %}
            <div>
                <h3>No event yet</h3>
            </div>
            {% endfor %}
        {% endif %}
    </div>
    </div>
</div>
{% endblock %}  

runo/templates/runo/paginator.html
<div class='pagination'>
    
        {% if page.has_previous %}
        <aside class='pageDetails'>
            <a href='?page={{ page.prev_page_number }}'>Previous</a>
        </aside> 
        {% endif %}
   
    <aside id='currentPage'>
        Page {{ page.number }} of {{ page.paginator.num_pages }}
    </aside>

    {% if page.has_next %}
    <aside class='pageDetails'>
        <a href='?page={{ page.next_page_number }}'>Next</a>
    </aside>
    {% endif %}


<style>
    #studentDetailsHouse .pagination{
        margin-top: 20px;
        display: flex;
        flex-wrap: wrap;
        
        align-items: center;
        justify-content: center;
    
    }
    
    #studentDetailsHouse .pagination > .pageDetails a{
        text-decoration: none;
        color: white;
  

    }

    #studentDetailsHouse .pagination > .pageDetails{
        padding: 10px;
        padding-left: 30px;
        padding-right: 30px;
        color: white;
        background-color: yellowgreen;
        border-radius: 20px;
        font-weight: bolder;
        margin-bottom: 20px;
        box-shadow: 0px 0px 10px 0px yellowgreen;

    }
    .night #studentDetailsHouse .pagination > .pageDetails{
        box-shadow: 0px 0px 0px 0px black;
        background-color: rgb(58, 81, 12);
    }
    #studentDetailsHouse #currentPage{
        padding: 10px;
        padding-left: 30px;
        padding-right: 30px;
        margin-bottom: 20px;

    }
</style>
</div>